services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    image: military-db-app
    container_name: military_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - SERVICE_ROLE=core
    volumes:
      - ./src:/var/www
    networks:
      - military-net

  web:
    image: nginx:alpine
    container_name: military_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - military-net

  front:
    image: node:20-alpine
    container_name: military_front
    working_dir: /var/www
    volumes:
      - ./front:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - military-net

  db:
    image: mysql:8.0
    container_name: military_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: military_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - military-net
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1

  redis:
    image: redis:alpine
    container_name: military_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - military-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: military_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - military-net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: military_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - military-net
    depends_on:
      - elasticsearch
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: military_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - military-net

  service_logger:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    image: military-logger-image
    container_name: military_logger_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - SERVICE_ROLE=logger
    volumes:
      - ./services/logger:/var/www
    depends_on:
      - rabbitmq
      - db
    networks:
      - military-net

  logger_web:
    image: nginx:alpine
    container_name: military_logger_web
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./services/logger:/var/www
      - ./docker/nginx/conf.d/logger.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service_logger
    networks:
      - military-net

  service_symfony:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: laravel
        uid: 1000
    image: military-symfony-app
    container_name: military_symfony_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - SERVICE_ROLE=symfony
    volumes:
      - ./services/symfony:/var/www
    depends_on:
      - rabbitmq
      - db
    networks:
      - military-net

  symfony_web:
    image: nginx:alpine
    container_name: military_symfony_web
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./services/symfony:/var/www
      - ./docker/nginx/conf.d/symfony.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service_symfony
    networks:
      - military-net

  service_go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    image: military-go
    container_name: military_go
    restart: unless-stopped
    ports:
      - "50051:50051"
    networks:
      - military-net

networks:
  military-net:
    driver: bridge

volumes:
  dbdata:
  elastic_data:
    driver: local