<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/report.proto

namespace Pdfgenerator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pdfgenerator.PdfResponse</code>
 */
class PdfResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes file_data = 1;</code>
     */
    protected $file_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes file_data = 1;</code>
     * @return string
     */
    public function getFileData()
    {
        return $this->file_data;
    }

    /**
     * Generated from protobuf field <code>bytes file_data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileData($var)
    {
        GPBUtil::checkString($var, False);
        $this->file_data = $var;

        return $this;
    }

}

