<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/report.proto

namespace Pdfgenerator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pdfgenerator.TableRow</code>
 */
class TableRow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string cells = 1;</code>
     */
    private $cells;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $cells
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string cells = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCells()
    {
        return $this->cells;
    }

    /**
     * Generated from protobuf field <code>repeated string cells = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCells($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cells = $arr;

        return $this;
    }

}

