<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/report.proto

namespace Pdfgenerator;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pdfgenerator.UniversalTableRequest</code>
 */
class UniversalTableRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';

    /**
     * Generated from protobuf field <code>repeated string headers = 2;</code>
     */
    private $headers;

    /**
     * Generated from protobuf field <code>repeated .pdfgenerator.TableRow rows = 3;</code>
     */
    private $rows;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $title
     * @type string[]|\Google\Protobuf\Internal\RepeatedField $headers
     * @type \Pdfgenerator\TableRow[]|\Google\Protobuf\Internal\RepeatedField $rows
     *                                                                        }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, true);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string headers = 2;</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>repeated string headers = 2;</code>
     *
     * @param  string[]|\Google\Protobuf\Internal\RepeatedField  $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->headers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pdfgenerator.TableRow rows = 3;</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * Generated from protobuf field <code>repeated .pdfgenerator.TableRow rows = 3;</code>
     *
     * @param  \Pdfgenerator\TableRow[]|\Google\Protobuf\Internal\RepeatedField  $var
     * @return $this
     */
    public function setRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pdfgenerator\TableRow::class);
        $this->rows = $arr;

        return $this;
    }
}
