<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/report.proto

namespace GPBMetadata\Proto;

class Report
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            '0ab5020a1270726f746f2f7265706f72742e70726f746f120c7064666765'.
            '6e657261746f72225d0a15556e6976657273616c5461626c655265717565'.
            '7374120d0a057469746c65180120012809120f0a07686561646572731802'.
            '2003280912240a04726f777318032003280b32162e70646667656e657261'.
            '746f722e5461626c65526f7722190a085461626c65526f77120d0a056365'.
            '6c6c7318012003280922200a0b506466526573706f6e736512110a096669'.
            '6c655f6461746118012001280c32650a0d5265706f727453657276696365'.
            '12540a1047656e65726174655461626c6550646612232e70646667656e65'.
            '7261746f722e556e6976657273616c5461626c65526571756573741a192e'.
            '70646667656e657261746f722e506466526573706f6e7365220042065a04'.
            '2e2f7062620670726f746f33'
        ), true);

        static::$is_initialized = true;
    }
}
